// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.throttle.version", 1);
user_pref("app.normandy.startupRolloutPrefs.layout.display-list.retain", true);
user_pref("app.normandy.startupRolloutPrefs.security.tls.version.fallback-limit", 4);
user_pref("app.normandy.user_id", "4e4f2a60-1c59-479b-b719-f40c98981ec7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1534499364);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1534499604);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1534499484);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1534499335);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7c803791-e60a-4fe1-b001-5dc9fe7702e8}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1534478400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1534499365);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1534499358320");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1534501169320");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1534499353573");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1534502953573");
user_pref("browser.search.countryCode", "UA");
user_pref("browser.search.region", "UA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1534499340");
user_pref("browser.slowStartup.averageTime", 11847);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180704192850");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1534499352797");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"fb284fb9-7012-488e-8558-473d77e501d1\",\"screenshots@mozilla.org\":\"59c64dd1-0eba-4849-accd-0a86d9eb2e0d\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1534499404);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180704192850");
user_pref("media.gmp-manager.lastCheck", 1534499403);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.throttle.version", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "d56fab16-5ba1-4fb7-94bd-31b74e1cfe88");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1534499327);
user_pref("toolkit.telemetry.cachedClientID", "ac404f87-e455-4bb2-8e86-4e1d50840b16");
user_pref("toolkit.telemetry.previousBuildID", "20180704192850");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
